project:
  name: "hello-world"
  version: "0.1.0"

build:
  target: executable
  output_dir: "build"
  optimization: 2
  linker_flags:
    - "-lm"
    - "-lpthread"
  source_dirs:
    - src/
  sources:
    - main2.utp
    #- IDrawable.utp
    #- Entity.utp
