#include "utopia/CodeGen/SimdIntrinsics.hpp"
#include "utopia/CodeGen/CodeGen.hpp"
#include "utopia/Common/Types.hpp"

#include <llvm/IR/Constants.h>
#include <llvm/IR/Intrinsics.h>
#include <llvm/IR/Module.h>
#include <llvm/Support/Alignment.h>

#include <cstdint>

namespace utopia {

/* Portable SIMD intrinsics.
 *
 * Every operation is implemented once and driven by the vector types that
 * appear at the call site. Utopia declares the ops with concrete signatures
 * in libs/prelude/lib/Simd/Core.utp (generated by
 * scripts/gen_simd_prelude.py); the lowering below maps them onto LLVM
 * fixed-length vector IR ('<4 x float>', '<16 x i8>', ...), which every
 * backend (SSE/AVX/AVX-512, NEON, SVE, RVV, ...) lowers to its native SIMD
 * instructions.
 */

namespace {

enum class SimdOp {
  /* arithmetic */
  Add, Sub, Mul, FDiv, SDiv, UDiv, SRem, URem,
  Sqrt, Neg, Abs, FMA,
  Min, Max, UMin, UMax,
  HAdd,
  /* bitwise / shifts */
  And, Or, Xor, Not,
  Shl, Shr, UShr,
  ShlScalar, ShrScalar, UShrScalar,
  /* comparisons: mask result (<L x i1>) */
  CmpEq, CmpNe, CmpLt, CmpLe, CmpGt, CmpGe,
  CmpUlt, CmpUle, CmpUgt, CmpUge,
  /* comparisons: all-ones result (same vector type as the operands) */
  CmpEqOnes, CmpNeOnes, CmpLtOnes, CmpLeOnes, CmpGtOnes, CmpGeOnes,
  CmpUltOnes, CmpUleOnes, CmpUgtOnes, CmpUgeOnes,
  /* selection / layout */
  Select, SelectSwap, BlendV,
  Shuffle, Extract, Insert,
  Splat, Make, MakeRev, Zero, SplatLane,
  MoveLH, MoveHL, UnpackLo, UnpackHi,
  /* memory */
  Load, LoadU, Store, StoreU, BroadcastLoad,
  /* reinterpretation */
  Convert, Bitcast,
  /* reductions */
  ReduceAdd, ReduceMin, ReduceMax, ReduceUMin, ReduceUMax,
  ReduceAnd, ReduceOr, ReduceXor,
  Any, All, Bitmask, SignMask,
};

struct SimdInfo {
  const VectorType *vecTy = nullptr;
  const Type *elemTy = nullptr;
  BuiltinKind elemKind = BuiltinKind::Void;
  uint64_t lanes = 0;
  unsigned elemBits = 0;
  llvm::Type *llElem = nullptr;
  llvm::FixedVectorType *llVec = nullptr;
  bool isFloat = false;
  bool isBool = false;
  bool isSigned = false;

  bool valid() const { return vecTy != nullptr; }
};

/* Maps a comparison flavor to an LLVM predicate. */
llvm::CmpInst::Predicate floatCmpPredicate(SimdOp op) {
  switch (op) {
  case SimdOp::CmpEq:
  case SimdOp::CmpEqOnes:
    return llvm::CmpInst::FCMP_UEQ; /* bitwise semantics: NaN == NaN */
  case SimdOp::CmpNe:
  case SimdOp::CmpNeOnes:
    return llvm::CmpInst::FCMP_UNE;
  case SimdOp::CmpLt:
  case SimdOp::CmpLtOnes:
    return llvm::CmpInst::FCMP_OLT;
  case SimdOp::CmpLe:
  case SimdOp::CmpLeOnes:
    return llvm::CmpInst::FCMP_OLE;
  case SimdOp::CmpGt:
  case SimdOp::CmpGtOnes:
    return llvm::CmpInst::FCMP_OGT;
  case SimdOp::CmpGe:
  case SimdOp::CmpGeOnes:
    return llvm::CmpInst::FCMP_OGE;
  default:
    return llvm::CmpInst::FCMP_UEQ;
  }
}

llvm::CmpInst::Predicate intCmpPredicate(SimdOp op, bool signedCmp) {
  switch (op) {
  case SimdOp::CmpEq:
  case SimdOp::CmpEqOnes:
    return llvm::CmpInst::ICMP_EQ;
  case SimdOp::CmpNe:
  case SimdOp::CmpNeOnes:
    return llvm::CmpInst::ICMP_NE;
  case SimdOp::CmpLt:
  case SimdOp::CmpLtOnes:
    return signedCmp ? llvm::CmpInst::ICMP_SLT : llvm::CmpInst::ICMP_ULT;
  case SimdOp::CmpLe:
  case SimdOp::CmpLeOnes:
    return signedCmp ? llvm::CmpInst::ICMP_SLE : llvm::CmpInst::ICMP_ULE;
  case SimdOp::CmpGt:
  case SimdOp::CmpGtOnes:
    return signedCmp ? llvm::CmpInst::ICMP_SGT : llvm::CmpInst::ICMP_UGT;
  case SimdOp::CmpGe:
  case SimdOp::CmpGeOnes:
    return signedCmp ? llvm::CmpInst::ICMP_SGE : llvm::CmpInst::ICMP_UGE;
  default:
    return llvm::CmpInst::ICMP_EQ;
  }
}

bool isOnesCmp(SimdOp op) {
  return op >= SimdOp::CmpEqOnes && op <= SimdOp::CmpUgeOnes;
}

class SimdOpIntrinsic : public Intrinsic {
  SimdOp op;

  /* helpers (members so the protected CodeGen proxies work) */

  SimdInfo getSimdInfo(CodeGen &cg, const Type *t) const {
    SimdInfo out;
    if (!t)
      return out;
    const Type *unqual = t->getUnqualifiedType();
    if (!llvm::isa<VectorType>(unqual))
      return out;
    const auto *vTy = static_cast<const VectorType *>(unqual);
    out.vecTy = vTy;
    out.elemTy = vTy->getElementType()->getUnqualifiedType();
    if (!llvm::isa<BuiltinType>(out.elemTy))
      return out;
    auto *bTy = static_cast<const BuiltinType *>(out.elemTy);
    out.elemKind = bTy->getBuiltinKind();
    out.lanes = vTy->getLanes();
    llvm::Type *llTy = Intrinsic::getLLVMType(cg, vTy);
    if (!llvm::isa<llvm::FixedVectorType>(llTy))
      return out;
    out.llVec = llvm::cast<llvm::FixedVectorType>(llTy);
    out.llElem = out.llVec->getElementType();
    out.elemBits = out.llElem->getScalarSizeInBits();
    out.isFloat = out.elemKind == BuiltinKind::Float32 ||
                  out.elemKind == BuiltinKind::Float64;
    out.isBool = out.elemKind == BuiltinKind::Bool;
    out.isSigned = out.elemKind == BuiltinKind::Int8 ||
                   out.elemKind == BuiltinKind::Int16 ||
                   out.elemKind == BuiltinKind::Int32 ||
                   out.elemKind == BuiltinKind::Int64;
    return out;
  }

  static llvm::Value *emitCompare(CodeGen &cg, llvm::IRBuilder<> &bld,
                                  SimdOp op, llvm::Value *lhs,
                                  llvm::Value *rhs, const SimdInfo &info) {
    if (info.isFloat)
      return bld.CreateFCmp(floatCmpPredicate(op), lhs, rhs);
    return bld.CreateICmp(intCmpPredicate(op, info.isSigned), lhs, rhs);
  }

  /* All-ones result: compare to a mask, sign-extend to the operand's
   * integer vector, then bitcast back to the operand's type (floats
   * included). */
  static llvm::Value *emitCompareOnes(CodeGen &cg, llvm::IRBuilder<> &bld,
                                      SimdOp op, llvm::Value *lhs,
                                      llvm::Value *rhs, const SimdInfo &info) {
    llvm::Value *mask = emitCompare(cg, bld, op, lhs, rhs, info);
    llvm::Type *intVecTy =
        llvm::FixedVectorType::get(bld.getIntNTy(info.elemBits), info.lanes);
    llvm::Value *ones = bld.CreateSExt(mask, intVecTy);
    if (info.isFloat)
      return bld.CreateBitCast(ones, info.llVec);
    return ones;
  }

  /* Packs an '<L x i1>' mask into an integer whose bits are the lane signs.
   * 'dstBits' is the width of the returned integer. */
  static llvm::Value *emitBitmaskPack(llvm::IRBuilder<> &bld,
                                      llvm::Value *mask,
                                      const SimdInfo &info,
                                      unsigned dstBits) {
    llvm::Type *packedTy = bld.getIntNTy(info.lanes);
    llvm::Value *packed = bld.CreateBitCast(mask, packedTy, "simd.mask");
    llvm::Type *dstTy = bld.getIntNTy(dstBits);
    if (packed->getType() == dstTy)
      return packed;
    return bld.CreateZExt(packed, dstTy, "simd.mask");
  }

  llvm::Value *emit(CodeGen &cg, const FunctionCallNode *node) const {
    llvm::IRBuilder<> &bld = getBuilder(cg);
    llvm::Module &mod = getModule(cg);

    const Type *retType = node->exprType;
    SimdInfo retInfo = getSimdInfo(cg, retType);

    auto fail = [&](const std::string &msg) -> llvm::Value * {
      reportError(cg, node->line, node->column, node->length, msg);
      return nullptr;
    };
    auto dispatchArg = [&](size_t i) -> llvm::Value * {
      if (i >= node->args.size())
        return nullptr;
      return cg.dispatch(node->args[i]);
    };
    /* As Integer-typed literals may arrive as i32, cast to the declared
     * usize before use. */
    auto toUsize = [&](llvm::Value *v) -> llvm::Value * {
      if (v->getType() != bld.getInt64Ty())
        return bld.CreateIntCast(v, bld.getInt64Ty(), false);
      return v;
    };
    auto constIndex = [&](size_t i, uint64_t max, int64_t &out) -> bool {
      llvm::Value *v = dispatchArg(i);
      if (!v)
        return false;
      if (auto *ci = llvm::dyn_cast<llvm::ConstantInt>(v)) {
        int64_t idx = ci->getSExtValue();
        if (idx < 0 || (uint64_t)idx >= max)
          return false;
        out = idx;
        return true;
      }
      return false;
    };

    switch (op) {
    /* arithmetic */
    case SimdOp::Add:
    case SimdOp::Sub:
    case SimdOp::Mul:
    case SimdOp::FDiv:
    case SimdOp::SDiv:
    case SimdOp::UDiv:
    case SimdOp::SRem:
    case SimdOp::URem: {
      llvm::Value *a = dispatchArg(0);
      llvm::Value *b = dispatchArg(1);
      if (!a || !b)
        return fail("Missing operands for SIMD arithmetic.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD arithmetic requires vector operands.");
      switch (op) {
      case SimdOp::Add:
        return info.isFloat ? bld.CreateFAdd(a, b) : bld.CreateAdd(a, b);
      case SimdOp::Sub:
        return info.isFloat ? bld.CreateFSub(a, b) : bld.CreateSub(a, b);
      case SimdOp::Mul:
        return info.isFloat ? bld.CreateFMul(a, b) : bld.CreateMul(a, b);
      case SimdOp::FDiv:
        return bld.CreateFDiv(a, b);
      case SimdOp::SDiv:
        return bld.CreateSDiv(a, b);
      case SimdOp::UDiv:
        return bld.CreateUDiv(a, b);
      case SimdOp::SRem:
        return bld.CreateSRem(a, b);
      case SimdOp::URem:
        return bld.CreateURem(a, b);
      default:
        return nullptr;
      }
    }
    case SimdOp::Sqrt: {
      llvm::Value *a = dispatchArg(0);
      if (!a)
        return fail("Missing operand for SIMD sqrt.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD sqrt requires a vector operand.");
      return bld.CreateIntrinsic(llvm::Intrinsic::sqrt, {info.llVec}, {a});
    }
    case SimdOp::Neg: {
      llvm::Value *a = dispatchArg(0);
      if (!a)
        return fail("Missing operand for SIMD negate.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD negate requires a vector operand.");
      return info.isFloat ? bld.CreateFNeg(a) : bld.CreateNeg(a);
    }
    case SimdOp::Abs: {
      llvm::Value *a = dispatchArg(0);
      if (!a)
        return fail("Missing operand for SIMD abs.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD abs requires a vector operand.");
      if (info.isFloat)
        return bld.CreateIntrinsic(llvm::Intrinsic::fabs, {info.llVec}, {a});
      llvm::Value *zero = llvm::Constant::getNullValue(info.llVec);
      llvm::Value *neg = bld.CreateNeg(a);
      llvm::Value *sel = bld.CreateICmpSLT(a, zero, "abs.sel");
      return bld.CreateSelect(sel, neg, a);
    }
    case SimdOp::FMA: {
      llvm::Value *a = dispatchArg(0);
      llvm::Value *b = dispatchArg(1);
      llvm::Value *c = dispatchArg(2);
      if (!a || !b || !c)
        return fail("Missing operands for SIMD fma.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD fma requires vector operands.");
      return bld.CreateIntrinsic(llvm::Intrinsic::fma, {info.llVec},
                               {a, b, c});
    }
    case SimdOp::Min:
    case SimdOp::Max:
    case SimdOp::UMin:
    case SimdOp::UMax: {
      llvm::Value *a = dispatchArg(0);
      llvm::Value *b = dispatchArg(1);
      if (!a || !b)
        return fail("Missing operands for SIMD min/max.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD min/max requires vector operands.");
      if (info.isFloat) {
        if (op == SimdOp::Min)
          return bld.CreateMinNum(a, b);
        if (op == SimdOp::Max)
          return bld.CreateMaxNum(a, b);
        return fail("Unsigned min/max requires integer vectors.");
      }
      llvm::Intrinsic::ID id = llvm::Intrinsic::smin;
      if (op == SimdOp::Min)
        id = info.isSigned ? llvm::Intrinsic::smin : llvm::Intrinsic::umin;
      else if (op == SimdOp::Max)
        id = info.isSigned ? llvm::Intrinsic::smax : llvm::Intrinsic::umax;
      else if (op == SimdOp::UMin)
        id = llvm::Intrinsic::umin;
      else if (op == SimdOp::UMax)
        id = llvm::Intrinsic::umax;
      return bld.CreateIntrinsic(id, {info.llVec}, {a, b});
    }
    case SimdOp::HAdd: {
      llvm::Value *a = dispatchArg(0);
      llvm::Value *b = dispatchArg(1);
      if (!a || !b)
        return fail("Missing operands for SIMD horizontal add.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD horizontal add requires vector operands.");
      /* even/odd interleave: (a0,a2,...,b0,b2,...) + (a1,a3,...,b1,b3,...) */
      llvm::SmallVector<int, 64> evenM, oddM;
      for (uint64_t i = 0; i < info.lanes; ++i) {
        evenM.push_back(2 * (int)i);
        oddM.push_back(2 * (int)i + 1);
      }
      llvm::Value *x = bld.CreateShuffleVector(a, b, evenM, "hadd.x");
      llvm::Value *y = bld.CreateShuffleVector(a, b, oddM, "hadd.y");
      return info.isFloat ? bld.CreateFAdd(x, y) : bld.CreateAdd(x, y);
    }

    /* bitwise */
    case SimdOp::And:
    case SimdOp::Or:
    case SimdOp::Xor:
    case SimdOp::Not: {
      llvm::Value *a = dispatchArg(0);
      if (!a)
        return fail("Missing operand for SIMD bitwise op.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD bitwise ops require vector operands.");

      auto toInt = [&](llvm::Value *v) -> llvm::Value * {
        if (info.isFloat)
          return bld.CreateBitCast(v, info.llVec, "bitwise.int");
        return v;
      };
      auto fromInt = [&](llvm::Value *v) -> llvm::Value * {
        if (info.isFloat)
          return bld.CreateBitCast(v, info.llVec, "bitwise.fp");
        return v;
      };

      llvm::Value *ai = toInt(a);
      llvm::Value *result = nullptr;
      if (op == SimdOp::Not) {
        llvm::Constant *allOnes = llvm::Constant::getAllOnesValue(info.llVec);
        result = bld.CreateXor(ai, allOnes, "simd.not");
      } else {
        llvm::Value *bi = toInt(dispatchArg(1));
        if (!bi)
          return fail("Missing operand for SIMD bitwise op.");
        if (op == SimdOp::And)
          result = bld.CreateAnd(ai, bi);
        else if (op == SimdOp::Or)
          result = bld.CreateOr(ai, bi);
        else
          result = bld.CreateXor(ai, bi);
      }
      return fromInt(result);
    }
    case SimdOp::Shl:
    case SimdOp::Shr:
    case SimdOp::UShr:
    case SimdOp::ShlScalar:
    case SimdOp::ShrScalar:
    case SimdOp::UShrScalar: {
      llvm::Value *a = dispatchArg(0);
      llvm::Value *b = dispatchArg(1);
      if (!a || !b)
        return fail("Missing operands for SIMD shift.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD shifts require vector operands.");
      if (info.isFloat)
        return fail("SIMD shifts require integer vectors.");
      bool isScalar = op == SimdOp::ShlScalar || op == SimdOp::ShrScalar ||
                      op == SimdOp::UShrScalar;
      if (isScalar) {
        if (b->getType() != info.llElem)
          b = bld.CreateIntCast(b, info.llElem, false);
        b = bld.CreateVectorSplat(info.lanes, b, "shift.splat");
      }
      if (op == SimdOp::Shl || op == SimdOp::ShlScalar)
        return bld.CreateShl(a, b);
      if (op == SimdOp::Shr || op == SimdOp::ShrScalar)
        return bld.CreateAShr(a, b);
      return bld.CreateLShr(a, b);
    }

    /* comparisons */
    case SimdOp::CmpEq:
    case SimdOp::CmpNe:
    case SimdOp::CmpLt:
    case SimdOp::CmpLe:
    case SimdOp::CmpGt:
    case SimdOp::CmpGe:
    case SimdOp::CmpUlt:
    case SimdOp::CmpUle:
    case SimdOp::CmpUgt:
    case SimdOp::CmpUge:
    case SimdOp::CmpEqOnes:
    case SimdOp::CmpNeOnes:
    case SimdOp::CmpLtOnes:
    case SimdOp::CmpLeOnes:
    case SimdOp::CmpGtOnes:
    case SimdOp::CmpGeOnes:
    case SimdOp::CmpUltOnes:
    case SimdOp::CmpUleOnes:
    case SimdOp::CmpUgtOnes:
    case SimdOp::CmpUgeOnes: {
      llvm::Value *a = dispatchArg(0);
      llvm::Value *rhs = dispatchArg(1);
      if (!a || !rhs)
        return fail("Missing operands for SIMD comparison.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD comparison requires vector operands.");
      if (isOnesCmp(op))
        return emitCompareOnes(cg, bld, op, a, rhs, info);
      return emitCompare(cg, bld, op, a, rhs, info);
    }

    /* selection */
    case SimdOp::Select: {
      llvm::Value *mask = dispatchArg(0);
      llvm::Value *a = dispatchArg(1);
      llvm::Value *b = dispatchArg(2);
      if (!mask || !a || !b)
        return fail("Missing operands for SIMD select.");
      return bld.CreateSelect(mask, a, b);
    }
    case SimdOp::SelectSwap: {
      /* x86 mask-blend semantics: dst = mask ? b : a. */
      llvm::Value *mask = dispatchArg(0);
      llvm::Value *a = dispatchArg(1);
      llvm::Value *b = dispatchArg(2);
      if (!mask || !a || !b)
        return fail("Missing operands for SIMD select.");
      return bld.CreateSelect(mask, b, a);
    }
    case SimdOp::BlendV: {
      /* x86 blendv semantics: the sign bit of each mask lane selects. */
      llvm::Value *mask = dispatchArg(0);
      llvm::Value *a = dispatchArg(1);
      llvm::Value *b = dispatchArg(2);
      if (!mask || !a || !b)
        return fail("Missing operands for SIMD blend.");
      SimdInfo maskInfo = getSimdInfo(cg, node->args[0]->exprType);
      if (!maskInfo.valid())
        return fail("SIMD blend requires a vector mask.");
      llvm::Value *m = mask;
      if (maskInfo.isFloat) {
        llvm::Type *intVecTy = llvm::FixedVectorType::get(
            bld.getIntNTy(maskInfo.elemBits), maskInfo.lanes);
        m = bld.CreateBitCast(m, intVecTy, "blend.mask.int");
      }
      llvm::Value *zero =
          llvm::Constant::getNullValue(m->getType());
      llvm::Value *sel = bld.CreateICmpSLT(m, zero, "blend.mask.bits");
      return bld.CreateSelect(sel, a, b);
    }

    /* layout */
    case SimdOp::Shuffle: {
      llvm::Value *a = dispatchArg(0);
      llvm::Value *b = dispatchArg(1);
      if (!a || !b)
        return fail("Missing operands for SIMD shuffle.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD shuffle requires vector operands.");
      if (node->args.size() != 2 + info.lanes)
        return fail("SIMD shuffle requires one index per lane.");
      llvm::SmallVector<int, 64> mask;
      for (uint64_t i = 0; i < info.lanes; ++i) {
        int64_t idx = -1;
        if (!constIndex(2 + i, 2 * info.lanes, idx))
          return fail("SIMD shuffle indices must be compile-time constants "
                      "in [0, 2 * lanes).");
        mask.push_back((int)idx);
      }
      return bld.CreateShuffleVector(a, b, mask, "simd.shuffle");
    }
    case SimdOp::Extract: {
      llvm::Value *v = dispatchArg(0);
      if (!v)
        return fail("Missing operand for SIMD extract.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD extract requires a vector operand.");
      llvm::Value *idx = dispatchArg(1);
      if (!idx)
        return fail("Missing lane index for SIMD extract.");
      return bld.CreateExtractElement(v, toUsize(idx), "simd.lane");
    }
    case SimdOp::Insert: {
      llvm::Value *v = dispatchArg(0);
      llvm::Value *x = dispatchArg(2);
      if (!v || !x)
        return fail("Missing operands for SIMD insert.");
      llvm::Value *idx = dispatchArg(1);
      if (!idx)
        return fail("Missing lane index for SIMD insert.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (info.valid() && x->getType() != info.llElem)
        x = cg.createImplicitCast(x, info.llElem, node->args[2]->exprType);
      return bld.CreateInsertElement(v, x, toUsize(idx), "simd.insert");
    }
    case SimdOp::Splat: {
      llvm::Value *x = dispatchArg(0);
      if (!x)
        return fail("Missing scalar for SIMD splat.");
      if (!retInfo.valid())
        return fail("SIMD splat must return a vector type.");
      /* Literals may arrive un-cast (float literals default to float64);
       * apply the declared parameter conversion like a regular call. */
      if (x->getType() != retInfo.llElem)
        x = cg.createImplicitCast(x, retInfo.llElem, node->args[0]->exprType);
      return bld.CreateVectorSplat(retInfo.lanes, x, "simd.splat");
    }
    case SimdOp::MakeRev: {
      /* C's _mm_set_ps(w,z,y,x) builds (x,y,z,w): reverse the arguments. */
      if (!retInfo.valid())
        return fail("SIMD make must return a vector type.");
      if (node->args.size() != retInfo.lanes)
        return fail("SIMD make requires one value per lane.");
      llvm::Value *result = llvm::PoisonValue::get(retInfo.llVec);
      for (uint64_t i = 0; i < retInfo.lanes; ++i) {
        uint64_t srcIdx = retInfo.lanes - 1 - i;
        llvm::Value *x = dispatchArg(srcIdx);
        if (!x)
          return fail("Missing lane value for SIMD make.");
        if (x->getType() != retInfo.llElem)
          x = cg.createImplicitCast(x, retInfo.llElem,
                                    node->args[srcIdx]->exprType);
        result = bld.CreateInsertElement(result, x, bld.getInt64(i));
      }
      return result;
    }
    case SimdOp::Make: {
      if (!retInfo.valid())
        return fail("SIMD make must return a vector type.");
      if (node->args.size() != retInfo.lanes)
        return fail("SIMD make requires one value per lane.");
      llvm::Value *result = llvm::PoisonValue::get(retInfo.llVec);
      for (uint64_t i = 0; i < retInfo.lanes; ++i) {
        llvm::Value *x = dispatchArg(i);
        if (!x)
          return fail("Missing lane value for SIMD make.");
        if (x->getType() != retInfo.llElem)
          x = cg.createImplicitCast(x, retInfo.llElem,
                                    node->args[i]->exprType);
        result = bld.CreateInsertElement(result, x, bld.getInt64(i));
      }
      return result;
    }
    case SimdOp::Zero: {
      if (!retInfo.valid())
        return fail("SIMD zero must return a vector type.");
      return llvm::Constant::getNullValue(retInfo.llVec);
    }
    case SimdOp::SplatLane: {
      llvm::Value *v = dispatchArg(0);
      if (!v)
        return fail("Missing operand for SIMD splat-lane.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD splat-lane requires a vector operand.");
      int64_t lane = 0;
      llvm::Value *idxVal = dispatchArg(1);
      if (idxVal) {
        if (auto *ci = llvm::dyn_cast<llvm::ConstantInt>(idxVal)) {
          lane = ci->getSExtValue();
          if (lane < 0 || (uint64_t)lane >= info.lanes)
            return fail("SIMD splat-lane index out of range.");
        } else {
          return fail("SIMD splat-lane index must be a constant.");
        }
      }
      llvm::Value *elem = bld.CreateExtractElement(v, bld.getInt64(lane));
      return bld.CreateVectorSplat(info.lanes, elem, "simd.broadcast");
    }
    case SimdOp::MoveLH:
    case SimdOp::MoveHL:
    case SimdOp::UnpackLo:
    case SimdOp::UnpackHi: {
      llvm::Value *a = dispatchArg(0);
      llvm::Value *b = dispatchArg(1);
      if (!a || !b)
        return fail("Missing operands for SIMD shuffle op.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD shuffle op requires vector operands.");
      /* 64-bit elements are paired per 128-bit group; everything else in
       * groups of four lanes (matches SSE unpack/movelh semantics). */
      uint64_t group = info.elemBits == 64 ? 2 : 4;
      uint64_t half = group / 2;
      llvm::SmallVector<int, 64> mask;
      for (uint64_t g = 0; g < info.lanes / group; ++g) {
        uint64_t base = g * group;
        switch (op) {
        case SimdOp::UnpackLo:
          /* (a0,b0,a1,b1) per 128-bit group. */
          for (uint64_t i = 0; i < half; ++i) {
            mask.push_back((int)(base + i));
            mask.push_back((int)(base + i + info.lanes));
          }
          break;
        case SimdOp::UnpackHi:
          /* (a2,b2,a3,b3) per 128-bit group. */
          for (uint64_t i = 0; i < half; ++i) {
            mask.push_back((int)(base + half + i));
            mask.push_back((int)(base + half + i + info.lanes));
          }
          break;
        case SimdOp::MoveLH:
          /* (a2,a3,b2,b3): concat high halves. */
          for (uint64_t i = 0; i < half; ++i)
            mask.push_back((int)(base + half + i));
          for (uint64_t i = 0; i < half; ++i)
            mask.push_back((int)(base + half + i + info.lanes));
          break;
        case SimdOp::MoveHL:
          /* (b2,b3,a2,a3): concat high halves, other order. */
          for (uint64_t i = 0; i < half; ++i)
            mask.push_back((int)(base + half + i + info.lanes));
          for (uint64_t i = 0; i < half; ++i)
            mask.push_back((int)(base + half + i));
          break;
        default:
          break;
        }
      }
      return bld.CreateShuffleVector(a, b, mask, "simd.shuffle");
    }

    /* memory */
    case SimdOp::Load:
    case SimdOp::LoadU:
    case SimdOp::BroadcastLoad: {
      llvm::Value *p = dispatchArg(0);
      if (!p)
        return fail("Missing pointer for SIMD load.");
      SimdInfo info =
          retInfo.valid() ? retInfo : getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD load must return a vector type.");
      llvm::Align align = op == SimdOp::LoadU
                              ? llvm::Align(1)
                              : mod.getDataLayout().getABITypeAlign(info.llVec);
      llvm::Value *loaded =
          bld.CreateAlignedLoad(info.llVec, p, align, "simd.load");
      if (op != SimdOp::BroadcastLoad)
        return loaded;
      llvm::Value *elem = bld.CreateExtractElement(loaded, bld.getInt64(0));
      return bld.CreateVectorSplat(info.lanes, elem, "simd.broadcast");
    }
    case SimdOp::Store:
    case SimdOp::StoreU: {
      /* Accept both (value, pointer) and (pointer, value) orders; the x86
       * C API passes the address first, the portable layer the value. */
      llvm::Value *a0 = dispatchArg(0);
      llvm::Value *a1 = dispatchArg(1);
      if (!a0 || !a1)
        return fail("Missing operands for SIMD store.");
      llvm::Value *v = nullptr;
      llvm::Value *p = nullptr;
      if (getSimdInfo(cg, node->args[0]->exprType).valid()) {
        v = a0;
        p = a1;
      } else {
        v = a1;
        p = a0;
      }
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        info = getSimdInfo(cg, node->args[1]->exprType);
      if (!info.valid())
        return fail("SIMD store requires a vector value.");
      llvm::Align align = op == SimdOp::StoreU
                              ? llvm::Align(1)
                              : mod.getDataLayout().getABITypeAlign(info.llVec);
      bld.CreateAlignedStore(v, p, align);
      return nullptr;
    }

    /* reinterpretation */
    case SimdOp::Convert: {
      llvm::Value *v = dispatchArg(0);
      if (!v)
        return fail("Missing operand for SIMD conversion.");
      if (!retInfo.valid())
        return fail("SIMD conversion must return a vector type.");
      SimdInfo srcInfo = getSimdInfo(cg, node->args[0]->exprType);
      if (!srcInfo.valid())
        return fail("SIMD conversion requires a vector operand.");
      if (srcInfo.lanes != retInfo.lanes)
        return fail("SIMD conversion requires matching lane counts.");

      auto asInt = [&](const SimdInfo &i) { return !i.isFloat && !i.isBool; };
      if (asInt(srcInfo) && asInt(retInfo)) {
        if (srcInfo.elemBits < retInfo.elemBits)
          return srcInfo.isSigned ? bld.CreateSExt(v, retInfo.llVec)
                                  : bld.CreateZExt(v, retInfo.llVec);
        if (srcInfo.elemBits > retInfo.elemBits)
          return bld.CreateTrunc(v, retInfo.llVec);
        return bld.CreateBitCast(v, retInfo.llVec);
      }
      if (srcInfo.isFloat && retInfo.isFloat) {
        if (srcInfo.elemBits < retInfo.elemBits)
          return bld.CreateFPExt(v, retInfo.llVec);
        if (srcInfo.elemBits > retInfo.elemBits)
          return bld.CreateFPTrunc(v, retInfo.llVec);
        return bld.CreateBitCast(v, retInfo.llVec);
      }
      if (asInt(srcInfo) && retInfo.isFloat)
        return srcInfo.isSigned ? bld.CreateSIToFP(v, retInfo.llVec)
                                : bld.CreateUIToFP(v, retInfo.llVec);
      if (srcInfo.isFloat && asInt(retInfo))
        return retInfo.isSigned ? bld.CreateFPToSI(v, retInfo.llVec)
                                : bld.CreateFPToUI(v, retInfo.llVec);
      return fail("Unsupported SIMD conversion.");
    }
    case SimdOp::Bitcast: {
      llvm::Value *v = dispatchArg(0);
      if (!v)
        return fail("Missing operand for SIMD bitcast.");
      if (!retInfo.valid())
        return fail("SIMD bitcast must return a vector type.");
      llvm::Type *srcTy = v->getType();
      if (!llvm::isa<llvm::FixedVectorType>(srcTy) ||
          mod.getDataLayout().getTypeSizeInBits(srcTy) !=
              mod.getDataLayout().getTypeSizeInBits(retInfo.llVec))
        return fail("SIMD bitcast requires equal total width.");
      return bld.CreateBitCast(v, retInfo.llVec);
    }

    /* reductions */
    case SimdOp::ReduceAdd:
    case SimdOp::ReduceMin:
    case SimdOp::ReduceMax:
    case SimdOp::ReduceUMin:
    case SimdOp::ReduceUMax:
    case SimdOp::ReduceAnd:
    case SimdOp::ReduceOr:
    case SimdOp::ReduceXor: {
      llvm::Value *v = dispatchArg(0);
      if (!v)
        return fail("Missing operand for SIMD reduction.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD reduction requires a vector operand.");
      switch (op) {
      case SimdOp::ReduceAdd:
        if (info.isFloat) {
          llvm::Constant *negZero =
              llvm::ConstantFP::getNegativeZero(info.llElem);
          return bld.CreateIntrinsic(llvm::Intrinsic::vector_reduce_fadd,
                                     {info.llVec},
                                     {negZero, v});
        }
        return bld.CreateIntrinsic(llvm::Intrinsic::vector_reduce_add,
                                 {info.llVec}, {v});
      case SimdOp::ReduceMin: {
        llvm::Intrinsic::ID id =
            info.isFloat
                ? llvm::Intrinsic::vector_reduce_fmin
                : (info.isSigned ? llvm::Intrinsic::vector_reduce_smin
                                 : llvm::Intrinsic::vector_reduce_umin);
        return bld.CreateIntrinsic(id, {info.llVec}, {v});
      }
      case SimdOp::ReduceMax: {
        llvm::Intrinsic::ID id =
            info.isFloat
                ? llvm::Intrinsic::vector_reduce_fmax
                : (info.isSigned ? llvm::Intrinsic::vector_reduce_smax
                                 : llvm::Intrinsic::vector_reduce_umax);
        return bld.CreateIntrinsic(id, {info.llVec}, {v});
      }
      case SimdOp::ReduceUMin:
        return bld.CreateIntrinsic(llvm::Intrinsic::vector_reduce_umin,
                                 {info.llVec}, {v});
      case SimdOp::ReduceUMax:
        return bld.CreateIntrinsic(llvm::Intrinsic::vector_reduce_umax,
                                 {info.llVec}, {v});
      case SimdOp::ReduceAnd:
        return bld.CreateIntrinsic(llvm::Intrinsic::vector_reduce_and,
                                 {info.llVec}, {v});
      case SimdOp::ReduceOr:
        return bld.CreateIntrinsic(llvm::Intrinsic::vector_reduce_or,
                                 {info.llVec}, {v});
      case SimdOp::ReduceXor:
        return bld.CreateIntrinsic(llvm::Intrinsic::vector_reduce_xor,
                                 {info.llVec}, {v});
      default:
        return nullptr;
      }
    }
    case SimdOp::Any:
    case SimdOp::All: {
      llvm::Value *v = dispatchArg(0);
      if (!v)
        return fail("Missing operand for SIMD any/all.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid() || !info.isBool)
        return fail("SIMD any/all requires a boolean mask vector.");
      llvm::Intrinsic::ID id = op == SimdOp::Any
                                   ? llvm::Intrinsic::vector_reduce_or
                                   : llvm::Intrinsic::vector_reduce_and;
      return bld.CreateIntrinsic(id, {info.llVec}, {v});
    }
    case SimdOp::Bitmask:
    case SimdOp::SignMask: {
      llvm::Value *v = dispatchArg(0);
      if (!v)
        return fail("Missing operand for SIMD bitmask.");
      SimdInfo info = getSimdInfo(cg, node->args[0]->exprType);
      if (!info.valid())
        return fail("SIMD bitmask requires a vector operand.");
      llvm::Value *mask = v;
      if (op == SimdOp::SignMask) {
        if (info.isFloat) {
          llvm::Type *intVecTy = llvm::FixedVectorType::get(
              bld.getIntNTy(info.elemBits), info.lanes);
          v = bld.CreateBitCast(v, intVecTy, "signmask.int");
        }
        llvm::Value *zero = llvm::Constant::getNullValue(v->getType());
        mask = bld.CreateICmpSLT(v, zero, "signmask.bits");
      } else if (!info.isBool) {
        return fail("SIMD bitmask requires a boolean mask vector.");
      }
      unsigned dstBits =
          retInfo.valid() ? retInfo.llElem->getIntegerBitWidth() : 64;
      return emitBitmaskPack(bld, mask, info, dstBits);
    }
    }
    return fail("Unhandled SIMD operation.");
  }

public:
  explicit SimdOpIntrinsic(SimdOp o) : op(o) {}

  llvm::Value *evaluateRuntime(CodeGen &cg,
                               const FunctionCallNode *node) const override {
    return emit(cg, node);
  }

  llvm::Constant *
  evaluateConstant(CodeGen &cg, const FunctionCallNode *node) const override {
    return nullptr;
  }
};

struct SimdOpEntry {
  const char *name;
  SimdOp op;
};

static const SimdOpEntry simdOpsTable[] = {
    {"simd_add", SimdOp::Add},
    {"simd_sub", SimdOp::Sub},
    {"simd_mul", SimdOp::Mul},
    {"simd_div", SimdOp::FDiv},
    {"simd_sdiv", SimdOp::SDiv},
    {"simd_udiv", SimdOp::UDiv},
    {"simd_srem", SimdOp::SRem},
    {"simd_urem", SimdOp::URem},
    {"simd_sqrt", SimdOp::Sqrt},
    {"simd_neg", SimdOp::Neg},
    {"simd_abs", SimdOp::Abs},
    {"simd_fma", SimdOp::FMA},
    {"simd_min", SimdOp::Min},
    {"simd_max", SimdOp::Max},
    {"simd_umin", SimdOp::UMin},
    {"simd_umax", SimdOp::UMax},
    {"simd_hadd", SimdOp::HAdd},
    {"simd_and", SimdOp::And},
    {"simd_or", SimdOp::Or},
    {"simd_xor", SimdOp::Xor},
    {"simd_not", SimdOp::Not},
    {"simd_shl", SimdOp::Shl},
    {"simd_shr", SimdOp::Shr},
    {"simd_ushr", SimdOp::UShr},
    {"simd_shl_scalar", SimdOp::ShlScalar},
    {"simd_shr_scalar", SimdOp::ShrScalar},
    {"simd_ushr_scalar", SimdOp::UShrScalar},
    {"simd_cmp_eq", SimdOp::CmpEq},
    {"simd_cmp_ne", SimdOp::CmpNe},
    {"simd_cmp_lt", SimdOp::CmpLt},
    {"simd_cmp_le", SimdOp::CmpLe},
    {"simd_cmp_gt", SimdOp::CmpGt},
    {"simd_cmp_ge", SimdOp::CmpGe},
    {"simd_cmp_ult", SimdOp::CmpUlt},
    {"simd_cmp_ule", SimdOp::CmpUle},
    {"simd_cmp_ugt", SimdOp::CmpUgt},
    {"simd_cmp_uge", SimdOp::CmpUge},
    {"simd_cmp_eq_ones", SimdOp::CmpEqOnes},
    {"simd_cmp_ne_ones", SimdOp::CmpNeOnes},
    {"simd_cmp_lt_ones", SimdOp::CmpLtOnes},
    {"simd_cmp_le_ones", SimdOp::CmpLeOnes},
    {"simd_cmp_gt_ones", SimdOp::CmpGtOnes},
    {"simd_cmp_ge_ones", SimdOp::CmpGeOnes},
    {"simd_cmp_ult_ones", SimdOp::CmpUltOnes},
    {"simd_cmp_ule_ones", SimdOp::CmpUleOnes},
    {"simd_cmp_ugt_ones", SimdOp::CmpUgtOnes},
    {"simd_cmp_uge_ones", SimdOp::CmpUgeOnes},
    {"simd_select", SimdOp::Select},
    {"simd_select_swap", SimdOp::SelectSwap},
    {"simd_blendv", SimdOp::BlendV},
    {"simd_shuffle", SimdOp::Shuffle},
    {"simd_extract", SimdOp::Extract},
    {"simd_insert", SimdOp::Insert},
    {"simd_splat", SimdOp::Splat},
    {"simd_make", SimdOp::Make},
    {"simd_make_rev", SimdOp::MakeRev},
    {"simd_zero", SimdOp::Zero},
    {"simd_splat_lane", SimdOp::SplatLane},
    {"simd_movelh", SimdOp::MoveLH},
    {"simd_movehl", SimdOp::MoveHL},
    {"simd_unpacklo", SimdOp::UnpackLo},
    {"simd_unpackhi", SimdOp::UnpackHi},
    {"simd_load", SimdOp::Load},
    {"simd_loadu", SimdOp::LoadU},
    {"simd_store", SimdOp::Store},
    {"simd_storeu", SimdOp::StoreU},
    {"simd_broadcast", SimdOp::BroadcastLoad},
    {"simd_convert", SimdOp::Convert},
    {"simd_bitcast", SimdOp::Bitcast},
    {"simd_reduce_add", SimdOp::ReduceAdd},
    {"simd_reduce_min", SimdOp::ReduceMin},
    {"simd_reduce_max", SimdOp::ReduceMax},
    {"simd_reduce_umin", SimdOp::ReduceUMin},
    {"simd_reduce_umax", SimdOp::ReduceUMax},
    {"simd_reduce_and", SimdOp::ReduceAnd},
    {"simd_reduce_or", SimdOp::ReduceOr},
    {"simd_reduce_xor", SimdOp::ReduceXor},
    {"simd_any", SimdOp::Any},
    {"simd_all", SimdOp::All},
    {"simd_bitmask", SimdOp::Bitmask},
    {"simd_signmask", SimdOp::SignMask},
};

} // namespace

void registerSimdIntrinsics(IntrinsicRegistry &registry) {
  for (const auto &entry : simdOpsTable) {
    registry.registerIntrinsic(entry.name,
                               std::make_unique<SimdOpIntrinsic>(entry.op));
  }
}

} // namespace utopia
