#!/usr/bin/env python3
"""Generates the Unicode case-mapping helpers for the prelude String.

Outputs the bodies of String._toUpperCp / String._toLowerCp as contiguous
codepoint-range checks (delta runs), covering the ranges most European
text uses: Latin-1 Supplement, Latin Extended-A/B/Additional, Greek and
Cyrillic. Codepoints outside those ranges (CJK, Arabic, ...) are left
unchanged by design; the caller handles the multi-character mappings
(sharp s, ligatures) separately.

The generated code is inserted into libs/prelude/lib/String.utp.
"""

import os
import unicodedata

ROOT = os.path.join(os.path.dirname(__file__), "..", "libs", "prelude", "lib")

# Ranges to cover, inclusive. ASCII is included so the generated tables
# stay the single source of truth for the case mapping.
RANGES = [
    (0x0000, 0x007F),  # ASCII
    (0x0080, 0x024F),  # Latin-1 Supplement + Extended-A/B
    (0x0370, 0x03FF),  # Greek
    (0x0400, 0x04FF),  # Cyrillic
    (0x1E00, 0x1EFF),  # Latin Extended Additional
]


def is_supported(cp):
    return any(lo <= cp <= hi for lo, hi in RANGES)


def mapping(cp, direction):
    ch = chr(cp)
    mapped = ch.upper() if direction == "upper" else ch.lower()
    if len(mapped) != 1:
        return None  # multi-character mapping, handled by the caller
    out = ord(mapped)
    if out == cp:
        return None  # unchanged
    # Keep mappings into ASCII (I -> i, dotless i -> I) and into the
    # covered ranges; anything else is out of scope.
    if out > 0x7E and not is_supported(out):
        return None
    return out


def delta_runs(direction):
    """Returns sorted (start, end, delta) runs of constant delta."""
    deltas = {}
    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            m = mapping(cp, direction)
            if m is not None:
                deltas[cp] = m - cp
    if not deltas:
        return []
    points = sorted(deltas)
    runs = []
    run_start = points[0]
    run_delta = deltas[points[0]]
    prev = points[0]
    for cp in points[1:]:
        if cp == prev + 1 and deltas[cp] == run_delta:
            prev = cp
            continue
        runs.append((run_start, prev, run_delta))
        run_start = cp
        run_delta = deltas[cp]
        prev = cp
    runs.append((run_start, prev, run_delta))
    return runs


def emit(direction):
    lines = []
    for start, end, delta in delta_runs(direction):
        if start == end:
            lines.append(
                "    if (cp == 0x%X) return cp %+d;" % (start, delta))
        else:
            lines.append("    if (cp >= 0x%X && cp <= 0x%X) return cp %+d;"
                         % (start, end, delta))
    return lines


def main():
    upper = emit("upper")
    lower = emit("lower")
    print("// generated ranges: upper=%d lower=%d" % (len(upper), len(lower)))
    out = []
    out.append("  /* Generated by scripts/gen_unicode_case.py. Maps a")
    out.append("   * codepoint to its upper-case form, or 0 when unchanged.")
    out.append("   * Covers Latin-1/Extended, Greek and Cyrillic. */")
    out.append("  private static int32 _toUpperCp(int32 cp) {")
    out.extend(upper)
    out.append("    return 0;")
    out.append("  }")
    out.append("")
    out.append("  /* Generated by scripts/gen_unicode_case.py. Maps a")
    out.append("   * codepoint to its lower-case form, or 0 when unchanged. */")
    out.append("  private static int32 _toLowerCp(int32 cp) {")
    out.extend(lower)
    out.append("    return 0;")
    out.append("  }")
    body = "\n".join(out)
    path = os.path.join(ROOT, "String.utp")
    src = open(path).read()
    begin = "  /* __UNICODE_CASE_GENERATED_BEGIN__ */"
    end = "  /* __UNICODE_CASE_GENERATED_END__ */"
    if begin not in src or end not in src:
        raise SystemExit("markers not found in String.utp")
    head, _, rest = src.partition(begin)
    _, _, tail = rest.partition(end)
    src = head + begin + "\n" + body + "\n" + end + tail
    open(path, "w").write(src)
    print("wrote", path)


if __name__ == "__main__":
    main()
